### ISSUE TITLE
todo-list

### ISSUE THREAD

**Issue by pictuga** [pictuga/morss#15]
List of small bugs / things yet to be implemented

## morss/morss.py

- [ ] limit number of lxml fromstring/tostring calls (slow)
- [x] move iTunes spaghetti code outside the main code
- [x] only download feed with full Opener (html friendly) if using feedify (mode =xpath)
- [x] accept `application/xhtml+xml` as rss mimetype (kinda wrong but still the case sometimes...)

## morss/readabilite.py

- [x] make relative url absolute
- [ ] use custom xpath rule
- [ ] use config file for site-by-side xpath rules
- [x] improve link density thingy

## morss/crawler.py

- [ ] Remove the from_304 crap
- [ ] double check exec order
- [ ] append HTTPRedirectHandler by hand (to force exec order)
- [ ] put cache handler first but w/o the handler_order
- [ ] put EncodingHandler before HTTPEquiv
- [x] check if 301 caching has to be done earlier

## morss/feedify.py

- [ ] do something about FB graph API 2.0 (drop it...?)

**Comment by pictuga** [comment]
Moved to https://git.pictuga.com/pictuga/morss/issues/1

**Comment by pictuga** [comment]
Changed my mind. Issues will be tracked here
